environment: development
development:
	southbound:
		end-point: 10.95.213.36
		port: 8080
		url: /iot/tt
	identifier: '8934075379000039586'
default:
	southbound:
		end-point: 127.0.0.1
		port: 8000
		url: /Stack/Receive/
	identifier: 8934071179000001899